config/routes.rb
Rails.application.routes.draw do
  root :to => "posts#index"

  resources :posts do
    resources :comments, :except => [:show, :index]
  end
  resources :users, :except => [:index]

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :text, :presence => true

  default_scope { order('published ASC') }
end

app/models/message.rb
class Message

  def initialize(attributes)
    @to = attributes[:to]
    @from = attributes[:from]
    @body = attributes[:body]
  end

  def send_sms
    begin
      response = RestClient::Request.new(
        :method => :post,
        :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => @body,
                      :To => @to,
                      :From => @from }
      ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      false
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user

  validates :title, :presence => true
  validates :entry, :presence => true

  default_scope { order('published DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password

  validates :username, :presence => true, :uniqueness => { :case_sensitive => false }
  validates :email, :presence => true, :uniqueness => { :case_sensitive => false }
  validates :phone, :uniqueness => true

  has_many :posts
  has_many :comments

  # has_attached_file :avatar, :styles => { :medium => '300x300>', :thumb => '100x100>' }
  # validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.published = Time.now
    @comment.user = current_user
    if @comment.save
      flash[:notice] = "Your comment has been successfully added, " + current_user.username + "!"
      redirect_to post_path(@post)
    else
      render :new
    end
  end

private
  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.published = Time.now
    if @post.save
      flash[:notice] = "Your post was successfully created."
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Your post was successfully edited."
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Your post was successfully deleted."
    redirect_to posts_path
  end

private
  def post_params
    params.require(:post).permit(:title, :entry)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You have successfully logged in."
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out successfully"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Your account has been successfully created, " + @user.username
      redirect_to log_in_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Your account has been successfully updated, " + @user.username
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :phone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<dt><%= comment.user.username %></dt>
<dd><%= comment.text %></dd>
<dd><time datetime="<%= comment.published.strftime('%Y-%m-%dT%H:%M%z') %>"><%= comment.published.strftime("Published on %B %d, %Y at %I:%M%P \(%Z\)") %></time></dd>

app/views/comments/_form.html.erb
<%= render "layouts/errors", :object => @comment %>

<%= form_for [@post, @comment], :html => { :class => "form-horizontal" } do |f| %>
  <div class="form-group">
    <%= f.label :text %><br />
    <%= f.text_area :text, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit :class => "btn btn-success" %>
    <%= link_to "Cancel", :back, :class => "btn btn-warning" %>
  </div>
<% end %>

app/views/comments/new.html.erb
<section class="col-md-12">
  <h1>New Comment For <%= @post.title %></h1>

  <%= render "form" %>
</section>

app/views/comments/new.js.erb
$('#new_comment_link').hide().after('<%= j render "form" %>');

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-warning" role="alert">
    <h3>¡Ouch, Zany Invalid Data!</h3>
    <p>Please fix the following errors:</p>
    <ul>
      <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<section>
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div data-alert class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <div><%= msg %></div>
      </div>
    <% end %>
  <% end %>
</section>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Posts Manager", root_path, :class => "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li role="presentation">
          <%= link_to posts_path do %>
            <span class="glyphicon glyphicon-list"></span> List all blog posts
          <% end %>
        </li>
        <% if current_user %>
        <li role="presentation">
          <%= link_to new_post_path do %>
            <span class="glyphicon glyphicon-plus"></span> Create a new blog post
          <% end %>
        </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
                <li role="presentation"><%= link_to "Account", user_path(current_user) %></li>
                <li role="presentation"><%= link_to "Log Out", log_out_path %></li>
            </ul>
          </li>
        <% else %>
          <li role="presentation"><%= link_to "Sign Up", new_user_path %></li>
          <li role="presentation"><%= link_to "Log In", log_in_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Posts Manager</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render "layouts/navbar" %>

    <main class="container">
      <%= render "layouts/flash" %>

      <%= yield %>
    </main>

    <footer>
      <div class="container">
        <p class="col-md-3 col-md-offset-3"><a href="//zulaica.info" target="_blank">▶︎▲▼⬆︎▶︎</a> made this.</p>
        <p class="col-md-3">Source available on <a href="//github.com/zulaica/posts_manager" target="_blank">GitHub</a>.</p>
      </div>
    </footer>
  </body>
</html>

app/views/posts/_create.js.erb
$('#new_comment').remove();
$('#new_comment_link').show();
$('#comments').prepend('<%= j render(@comment) %>')

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>

<%= form_for @post, :html => { :class => "form-horizontal" } do |f| %>
  <div class="form-group">
    <%= f.label :title, :class => "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :entry, :class => "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.text_area :entry, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-10 col-md-offset-2">
      <%= f.submit :class => "btn btn-success" %>
      <%= link_to "Cancel", :back, :class => "btn btn-warning" %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%= link_to post_path(post) do %>
  <dt><%= post.title %></dt>
  <dd>Published by <%= post.user.username %> on <time datetime="<%= post.published.strftime('%Y-%m-%dT%H:%M%z') %>"><%= post.published.strftime("%B %d, %Y at %I:%M%P \(%Z\)") %></time></dd>
<% end %>

app/views/posts/edit.html.erb
<section class="col-md-12">
  <h1>Edit Post</h1>

  <%= render "form" %>
</section>

app/views/posts/index.html.erb
<section>
  <h1>All Posts</h1>

  <dl>
    <%= render(@posts) || "There are no posts yet!" %>
  </dl>
</section>

app/views/posts/new.html.erb
<section class="col-md-12">
  <h1>New Post</h1>

  <%= render "form" %>
</section>

app/views/posts/show.html.erb
<article class="col-md-8">
  <header>
    <h1><%= @post.title %></h1>
    <p>Published by <%= @post.user.username %> on <time datetime="<%= @post.published.strftime('%Y-%m-%dT%H:%M%z') %>"><%= @post.published.strftime("%B %d, %Y at %I:%M%P \(%Z\)") %></time></p>
  </header>

  <section>
    <p><%= h(@post.entry).gsub(/\n/, "</p><p>").html_safe %></p>
  </section>

  <section>
    <h2>Comments</h2>
    <dl id="comments">
      <%= render(@post.comments) || "There are no comments yet!" %>
    </dl>
    <% if current_user %>
      <p><%= link_to "Add a comment", new_post_comment_path(@post), id: "new_comment_link", remote: true %></p>
    <% else %>
      <p>You must have an account to post a comment. <%= link_to "Sign Up", new_user_path %> | <%= link_to "Log In", log_in_path %>
    <% end %>
  </section>
</article>

<aside class="col-md-4">
  <% if current_user == @post.user %>
    <h1>Manage this post</h1>
    <ul class="list-unstyled">
      <li><%= link_to "Edit this post", edit_post_path(@post), :class => "btn btn-default" %></li>
      <li><%= link_to "Delete this post", post_path(@post), :data => { :confirm => "Are you sure? This can't be undone.", :method => "delete" }, :class => "btn btn-danger" %></li>
    </ul>
  <% end %>
</aside>

app/views/tasks/_form.html.erb
<%= render "layouts/errors", :object => @post %>

<%= form_for [@post, @comment], :html => { :class => "form-horizontal" } do |f| %>
<div class="form-group">
  <%= f.label :author, :class => "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :author, :class => "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :text, :class => "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_area :text, :class => "form-control" %>
  </div>
</div>
<div class="form-group">
  <div class="col-md-10 col-md-offset-2">
    <%= f.submit :class => "btn btn-success" %>
    <%= link_to "Cancel", :back, :class => "btn btn-warning" %>
  </div>
</div>
<% end %>

app/views/tasks/new.html.erb
<section class="col-md-12">
  <h1>New Comment For <%= @post.title %></h1>

  <%= render "form" %>
</section>

app/views/users/_form.html.erb
<%= render "layouts/errors", :object => @user %>

<%= form_for @user, :html =>{ :multipart => true, :class => "form-horizontal" } do |f| %>
<div class="form-group">
  <%= f.label :username, :class => "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :username, :class => "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :email, :class => "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :email, :class => "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :phone, :class => "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :phone, :class => "form-control" %>
  </div>
</div>
<% unless current_user %>
  <div class="form-group">
    <%= f.label :password, :class => "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.password_field :password, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, :class => "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.password_field :password_confirmation, :class => "form-control" %>
    </div>
  </div>
<% end %>
<div class="form-group">
  <div class="col-md-10 col-md-offset-2">
    <%= f.submit "Submit", :class => "btn btn-success" %>
    <%= link_to "Cancel", :back, :class => "btn btn-warning" %>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<% if current_user %>
  <section class="col-md-12">
    <h1>Edit your account</h1>

    <%= render "form" %>
  </section>
<% else %>
  <section>
    <h1>You must be logged in to edit your account.</h1>
  </section>
<% end %>

app/views/users/new.html.erb
<section class="col-md-12">
  <h1>New User Signup</h1>

  <%= render "form" %>
</section>

app/views/users/show.html.erb
<article class="col-md-8">
  <header>
    <h1>Your Posts</h1>
  </header>

  <section>
    <dl>
      <%= render(@user.posts) || "You don't have any posts yet!" %>
    </dl>
  </section>
</article>

<aside class="col-md-4">
  <%# if @user.avatar_file_name %>
    <%#= image_tag @user.avatar.url(:thumb) %>
  <%# end %>
  <dl>
    <dt>Username</dt>
    <dd><%= @user.username %></dd>
    <dt>Email</dt>
    <dd><%= @user.email %></dd>
    <dt>Phone</dt>
    <dd><%= @user.phone %></dd>
  </dl>
  <% if current_user == @user %>
    <p><%= link_to "Edit your account", edit_user_path, :class => "btn btn-default" %></p>
  <% end %>
</aside>